Repository skoczen/will, pull requests merged in 2021-03, with the labels that each got.

#428 Switch to slack_sdk and add support to ignore users and send files
  docs/config.md
  will/__init__.py
  will/backends/encryption/aes.py
  will/backends/io_adapters/base.py
  will/backends/io_adapters/slack.py
  will/main.py
  will/plugin.py
  will/plugins/help/help.py
  will/plugins/help/programmer_help.py
  will/requirements/base.txt
  will/requirements/slack.txt
  will/utils.py
Labels: enhancement

#435 Update required_settings message for SlackBackend to current process
  will/backends/io_adapters/slack.py
Labels: enhancement

#434 Pin aiohttp version for slack_sdk
  will/requirements/slack.txt
Labels: dependencies

#432 Travis Fix, Github Actions, heroku fix
  .github/workflows/python-app.yml
  .travis.yml
  runtime.txt
  setup.py
  tox.ini
  will/plugins/productivity/remind.py
  will/requirements/base.txt
  will/requirements/dev.txt
  will/tests/test_plugin.py
Labels: dependencies, enhancement
